//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DealerInfo"/&gt;
 *         &lt;element ref="{}ProgramInfo"/&gt;
 *         &lt;element ref="{}PriceRuleInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dealerInfo",
    "programInfo",
    "priceRuleInfo"
})
@XmlRootElement(name = "AdminPortal")
public class AdminPortal {

    @XmlElement(name = "DealerInfo", required = true)
    protected DealerInfo dealerInfo;
    @XmlElement(name = "ProgramInfo", required = true)
    protected ProgramInfo programInfo;
    @XmlElement(name = "PriceRuleInfo", required = true)
    protected PriceRuleInfo priceRuleInfo;

    /**
     * Gets the value of the dealerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DealerInfo }
     *     
     */
    public DealerInfo getDealerInfo() {
        return dealerInfo;
    }

    /**
     * Sets the value of the dealerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealerInfo }
     *     
     */
    public void setDealerInfo(DealerInfo value) {
        this.dealerInfo = value;
    }

    /**
     * Gets the value of the programInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramInfo }
     *     
     */
    public ProgramInfo getProgramInfo() {
        return programInfo;
    }

    /**
     * Sets the value of the programInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramInfo }
     *     
     */
    public void setProgramInfo(ProgramInfo value) {
        this.programInfo = value;
    }

    /**
     * Gets the value of the priceRuleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PriceRuleInfo }
     *     
     */
    public PriceRuleInfo getPriceRuleInfo() {
        return priceRuleInfo;
    }

    /**
     * Sets the value of the priceRuleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceRuleInfo }
     *     
     */
    public void setPriceRuleInfo(PriceRuleInfo value) {
        this.priceRuleInfo = value;
    }

}
