//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Admin package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("", "Email");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Phone_QNAME = new QName("", "Phone");
    private final static QName _Fax_QNAME = new QName("", "Fax");
    private final static QName _CompanyName_QNAME = new QName("", "Company_name");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _Province_QNAME = new QName("", "Province");
    private final static QName _PostalCode_QNAME = new QName("", "Postal_code");
    private final static QName _InternalId_QNAME = new QName("", "Internal_id");
    private final static QName _ContactTitle_QNAME = new QName("", "Contact_title");
    private final static QName _LicenseNo_QNAME = new QName("", "License_no");
    private final static QName _RegistrationGST_QNAME = new QName("", "Registration_GST");
    private final static QName _RegistrationPST_QNAME = new QName("", "Registration_PST");
    private final static QName _Group_QNAME = new QName("", "Group");
    private final static QName _Notes_QNAME = new QName("", "Notes");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _EnglishPdf_QNAME = new QName("", "English_Pdf");
    private final static QName _FrenchPdf_QNAME = new QName("", "French_Pdf");
    private final static QName _EligibilityYears_QNAME = new QName("", "Eligibility_Years");
    private final static QName _EligibilityKmPerHr_QNAME = new QName("", "Eligibility_KmPerHr");
    private final static QName _TermMonths_QNAME = new QName("", "Term_Months");
    private final static QName _TermKm_QNAME = new QName("", "Term_Km");
    private final static QName _FranchiseAmount_QNAME = new QName("", "Franchise_Amount");
    private final static QName _RepairAmountPerVisit_QNAME = new QName("", "Repair_Amount_Per_Visit");
    private final static QName _RepairAmountTotal_QNAME = new QName("", "Repair_Amount_Total");
    private final static QName _RepairAmountText_QNAME = new QName("", "Repair_Amount_Text");
    private final static QName _EligibilityCategory_QNAME = new QName("", "Eligibility_Category");
    private final static QName _FuelTypeEligibility_QNAME = new QName("", "FuelType_Eligibility");
    private final static QName _VehicleType_QNAME = new QName("", "Vehicle_type");
    private final static QName _Code_QNAME = new QName("", "Code");
    private final static QName _Attribute_QNAME = new QName("", "Attribute");
    private final static QName _Operator_QNAME = new QName("", "Operator");
    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _Position_QNAME = new QName("", "Position");
    private final static QName _ApplyRuleIf_QNAME = new QName("", "Apply_rule_if");
    private final static QName _Apply_QNAME = new QName("", "Apply");
    private final static QName _Amount_QNAME = new QName("", "Amount");
    private final static QName _StopFurtherProcessing_QNAME = new QName("", "Stop_further_processing");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Admin
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dealer }
     * 
     */
    public Dealer createDealer() {
        return new Dealer();
    }

    /**
     * Create an instance of {@link ProgTerm }
     * 
     */
    public ProgTerm createProgTerm() {
        return new ProgTerm();
    }

    /**
     * Create an instance of {@link ProgramTerms }
     * 
     */
    public ProgramTerms createProgramTerms() {
        return new ProgramTerms();
    }

    /**
     * Create an instance of {@link ProgOption }
     * 
     */
    public ProgOption createProgOption() {
        return new ProgOption();
    }

    /**
     * Create an instance of {@link WarrantyCondition }
     * 
     */
    public WarrantyCondition createWarrantyCondition() {
        return new WarrantyCondition();
    }

    /**
     * Create an instance of {@link Wholesaler }
     * 
     */
    public Wholesaler createWholesaler() {
        return new Wholesaler();
    }

    /**
     * Create an instance of {@link ProgramOptions }
     * 
     */
    public ProgramOptions createProgramOptions() {
        return new ProgramOptions();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link PriceRule }
     * 
     */
    public PriceRule createPriceRule() {
        return new PriceRule();
    }

    /**
     * Create an instance of {@link DealerInfo }
     * 
     */
    public DealerInfo createDealerInfo() {
        return new DealerInfo();
    }

    /**
     * Create an instance of {@link ProgramInfo }
     * 
     */
    public ProgramInfo createProgramInfo() {
        return new ProgramInfo();
    }

    /**
     * Create an instance of {@link PriceRuleInfo }
     * 
     */
    public PriceRuleInfo createPriceRuleInfo() {
        return new PriceRuleInfo();
    }

    /**
     * Create an instance of {@link AdminPortal }
     * 
     */
    public AdminPortal createAdminPortal() {
        return new AdminPortal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Company_name")
    public JAXBElement<String> createCompanyName(String value) {
        return new JAXBElement<String>(_CompanyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Province")
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<String>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Postal_code")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Internal_id")
    public JAXBElement<String> createInternalId(String value) {
        return new JAXBElement<String>(_InternalId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Contact_title")
    public JAXBElement<String> createContactTitle(String value) {
        return new JAXBElement<String>(_ContactTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "License_no")
    public JAXBElement<String> createLicenseNo(String value) {
        return new JAXBElement<String>(_LicenseNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Registration_GST")
    public JAXBElement<String> createRegistrationGST(String value) {
        return new JAXBElement<String>(_RegistrationGST_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Registration_PST")
    public JAXBElement<String> createRegistrationPST(String value) {
        return new JAXBElement<String>(_RegistrationPST_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Group")
    public JAXBElement<String> createGroup(String value) {
        return new JAXBElement<String>(_Group_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Notes")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "English_Pdf")
    public JAXBElement<String> createEnglishPdf(String value) {
        return new JAXBElement<String>(_EnglishPdf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "French_Pdf")
    public JAXBElement<String> createFrenchPdf(String value) {
        return new JAXBElement<String>(_FrenchPdf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Eligibility_Years")
    public JAXBElement<String> createEligibilityYears(String value) {
        return new JAXBElement<String>(_EligibilityYears_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Eligibility_KmPerHr")
    public JAXBElement<String> createEligibilityKmPerHr(String value) {
        return new JAXBElement<String>(_EligibilityKmPerHr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Term_Months")
    public JAXBElement<String> createTermMonths(String value) {
        return new JAXBElement<String>(_TermMonths_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Term_Km")
    public JAXBElement<String> createTermKm(String value) {
        return new JAXBElement<String>(_TermKm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Franchise_Amount")
    public JAXBElement<String> createFranchiseAmount(String value) {
        return new JAXBElement<String>(_FranchiseAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Repair_Amount_Per_Visit")
    public JAXBElement<String> createRepairAmountPerVisit(String value) {
        return new JAXBElement<String>(_RepairAmountPerVisit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Repair_Amount_Total")
    public JAXBElement<String> createRepairAmountTotal(String value) {
        return new JAXBElement<String>(_RepairAmountTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Repair_Amount_Text")
    public JAXBElement<String> createRepairAmountText(String value) {
        return new JAXBElement<String>(_RepairAmountText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Eligibility_Category")
    public JAXBElement<String> createEligibilityCategory(String value) {
        return new JAXBElement<String>(_EligibilityCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "FuelType_Eligibility")
    public JAXBElement<String> createFuelTypeEligibility(String value) {
        return new JAXBElement<String>(_FuelTypeEligibility_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Vehicle_type")
    public JAXBElement<String> createVehicleType(String value) {
        return new JAXBElement<String>(_VehicleType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Attribute")
    public JAXBElement<String> createAttribute(String value) {
        return new JAXBElement<String>(_Attribute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Operator")
    public JAXBElement<String> createOperator(String value) {
        return new JAXBElement<String>(_Operator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Position")
    public JAXBElement<String> createPosition(String value) {
        return new JAXBElement<String>(_Position_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Apply_rule_if")
    public JAXBElement<String> createApplyRuleIf(String value) {
        return new JAXBElement<String>(_ApplyRuleIf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Apply")
    public JAXBElement<String> createApply(String value) {
        return new JAXBElement<String>(_Apply_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Stop_further_processing")
    public JAXBElement<String> createStopFurtherProcessing(String value) {
        return new JAXBElement<String>(_StopFurtherProcessing_QNAME, String.class, null, value);
    }

}
