//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;element ref="{}Position" minOccurs="0"/&gt;
 *         &lt;element ref="{}Apply_rule_if" minOccurs="0"/&gt;
 *         &lt;element ref="{}Conditions" minOccurs="0"/&gt;
 *         &lt;element ref="{}Apply" minOccurs="0"/&gt;
 *         &lt;element ref="{}Amount" minOccurs="0"/&gt;
 *         &lt;element ref="{}Stop_further_processing" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "position",
    "applyRuleIf",
    "conditions",
    "apply",
    "amount",
    "stopFurtherProcessing"
})
@XmlRootElement(name = "PriceRule")
public class PriceRule {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Position")
    protected String position;
    @XmlElement(name = "Apply_rule_if")
    protected String applyRuleIf;
    @XmlElement(name = "Conditions")
    protected Conditions conditions;
    @XmlElement(name = "Apply")
    protected String apply;
    @XmlElement(name = "Amount")
    protected String amount;
    @XmlElement(name = "Stop_further_processing")
    protected String stopFurtherProcessing;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the applyRuleIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyRuleIf() {
        return applyRuleIf;
    }

    /**
     * Sets the value of the applyRuleIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyRuleIf(String value) {
        this.applyRuleIf = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApply(String value) {
        this.apply = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the stopFurtherProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopFurtherProcessing() {
        return stopFurtherProcessing;
    }

    /**
     * Sets the value of the stopFurtherProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopFurtherProcessing(String value) {
        this.stopFurtherProcessing = value;
    }

}
