//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Eligibility_Years"/&gt;
 *         &lt;element ref="{}Eligibility_KmPerHr" minOccurs="0"/&gt;
 *         &lt;element ref="{}Term_Months" minOccurs="0"/&gt;
 *         &lt;element ref="{}Term_Km" minOccurs="0"/&gt;
 *         &lt;element ref="{}Franchise_Amount" minOccurs="0"/&gt;
 *         &lt;element ref="{}Repair_Amount_Per_Visit" minOccurs="0"/&gt;
 *         &lt;element ref="{}Repair_Amount_Total" minOccurs="0"/&gt;
 *         &lt;element ref="{}Repair_Amount_Text" minOccurs="0"/&gt;
 *         &lt;element ref="{}Eligibility_Category" minOccurs="0"/&gt;
 *         &lt;element ref="{}FuelType_Eligibility" minOccurs="0"/&gt;
 *         &lt;element ref="{}Vehicle_type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eligibilityYears",
    "eligibilityKmPerHr",
    "termMonths",
    "termKm",
    "franchiseAmount",
    "repairAmountPerVisit",
    "repairAmountTotal",
    "repairAmountText",
    "eligibilityCategory",
    "fuelTypeEligibility",
    "vehicleType"
})
@XmlRootElement(name = "ProgTerm")
public class ProgTerm {

    @XmlElement(name = "Eligibility_Years", required = true)
    protected String eligibilityYears;
    @XmlElement(name = "Eligibility_KmPerHr")
    protected String eligibilityKmPerHr;
    @XmlElement(name = "Term_Months")
    protected String termMonths;
    @XmlElement(name = "Term_Km")
    protected String termKm;
    @XmlElement(name = "Franchise_Amount")
    protected String franchiseAmount;
    @XmlElement(name = "Repair_Amount_Per_Visit")
    protected String repairAmountPerVisit;
    @XmlElement(name = "Repair_Amount_Total")
    protected String repairAmountTotal;
    @XmlElement(name = "Repair_Amount_Text")
    protected String repairAmountText;
    @XmlElement(name = "Eligibility_Category")
    protected String eligibilityCategory;
    @XmlElement(name = "FuelType_Eligibility")
    protected String fuelTypeEligibility;
    @XmlElement(name = "Vehicle_type")
    protected String vehicleType;

    /**
     * Gets the value of the eligibilityYears property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityYears() {
        return eligibilityYears;
    }

    /**
     * Sets the value of the eligibilityYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityYears(String value) {
        this.eligibilityYears = value;
    }

    /**
     * Gets the value of the eligibilityKmPerHr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityKmPerHr() {
        return eligibilityKmPerHr;
    }

    /**
     * Sets the value of the eligibilityKmPerHr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityKmPerHr(String value) {
        this.eligibilityKmPerHr = value;
    }

    /**
     * Gets the value of the termMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermMonths() {
        return termMonths;
    }

    /**
     * Sets the value of the termMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermMonths(String value) {
        this.termMonths = value;
    }

    /**
     * Gets the value of the termKm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermKm() {
        return termKm;
    }

    /**
     * Sets the value of the termKm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermKm(String value) {
        this.termKm = value;
    }

    /**
     * Gets the value of the franchiseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFranchiseAmount() {
        return franchiseAmount;
    }

    /**
     * Sets the value of the franchiseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFranchiseAmount(String value) {
        this.franchiseAmount = value;
    }

    /**
     * Gets the value of the repairAmountPerVisit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairAmountPerVisit() {
        return repairAmountPerVisit;
    }

    /**
     * Sets the value of the repairAmountPerVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairAmountPerVisit(String value) {
        this.repairAmountPerVisit = value;
    }

    /**
     * Gets the value of the repairAmountTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairAmountTotal() {
        return repairAmountTotal;
    }

    /**
     * Sets the value of the repairAmountTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairAmountTotal(String value) {
        this.repairAmountTotal = value;
    }

    /**
     * Gets the value of the repairAmountText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairAmountText() {
        return repairAmountText;
    }

    /**
     * Sets the value of the repairAmountText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairAmountText(String value) {
        this.repairAmountText = value;
    }

    /**
     * Gets the value of the eligibilityCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityCategory() {
        return eligibilityCategory;
    }

    /**
     * Sets the value of the eligibilityCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityCategory(String value) {
        this.eligibilityCategory = value;
    }

    /**
     * Gets the value of the fuelTypeEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelTypeEligibility() {
        return fuelTypeEligibility;
    }

    /**
     * Sets the value of the fuelTypeEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelTypeEligibility(String value) {
        this.fuelTypeEligibility = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

}
