//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;element ref="{}Description" minOccurs="0"/&gt;
 *         &lt;element ref="{}Code" minOccurs="0"/&gt;
 *         &lt;element ref="{}WarrantyCondition" minOccurs="0"/&gt;
 *         &lt;element ref="{}Wholesaler" minOccurs="0"/&gt;
 *         &lt;element ref="{}ProgramOptions" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "description",
    "code",
    "warrantyCondition",
    "wholesaler",
    "programOptions"
})
@XmlRootElement(name = "Program")
public class Program {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "WarrantyCondition")
    protected WarrantyCondition warrantyCondition;
    @XmlElement(name = "Wholesaler")
    protected Wholesaler wholesaler;
    @XmlElement(name = "ProgramOptions")
    protected ProgramOptions programOptions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the warrantyCondition property.
     * 
     * @return
     *     possible object is
     *     {@link WarrantyCondition }
     *     
     */
    public WarrantyCondition getWarrantyCondition() {
        return warrantyCondition;
    }

    /**
     * Sets the value of the warrantyCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarrantyCondition }
     *     
     */
    public void setWarrantyCondition(WarrantyCondition value) {
        this.warrantyCondition = value;
    }

    /**
     * Gets the value of the wholesaler property.
     * 
     * @return
     *     possible object is
     *     {@link Wholesaler }
     *     
     */
    public Wholesaler getWholesaler() {
        return wholesaler;
    }

    /**
     * Sets the value of the wholesaler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wholesaler }
     *     
     */
    public void setWholesaler(Wholesaler value) {
        this.wholesaler = value;
    }

    /**
     * Gets the value of the programOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramOptions }
     *     
     */
    public ProgramOptions getProgramOptions() {
        return programOptions;
    }

    /**
     * Sets the value of the programOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramOptions }
     *     
     */
    public void setProgramOptions(ProgramOptions value) {
        this.programOptions = value;
    }

}
