//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.29 at 06:53:15 PM ICT 
//


package ProjectContext.BusinessObject.Admin;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Name"/&gt;
 *         &lt;element ref="{}Description"/&gt;
 *         &lt;element ref="{}English_Pdf"/&gt;
 *         &lt;element ref="{}French_Pdf"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "description",
    "englishPdf",
    "frenchPdf"
})
@XmlRootElement(name = "WarrantyCondition")
public class WarrantyCondition {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "English_Pdf", required = true)
    protected String englishPdf;
    @XmlElement(name = "French_Pdf", required = true)
    protected String frenchPdf;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the englishPdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglishPdf() {
        return englishPdf;
    }

    /**
     * Sets the value of the englishPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglishPdf(String value) {
        this.englishPdf = value;
    }

    /**
     * Gets the value of the frenchPdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrenchPdf() {
        return frenchPdf;
    }

    /**
     * Sets the value of the frenchPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrenchPdf(String value) {
        this.frenchPdf = value;
    }

}
