//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}QuoteInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quoteInfo",
    "vehicleInfo",
    "invoiceInfo"
})
@XmlRootElement(name = "DealerPortal")
public class DealerPortal {

    @XmlElement(name = "QuoteInfo", required = true)
    protected QuoteInfo quoteInfo;

    @XmlElement(name = "VehicleInfo", required = true)
    protected VehicleInfo vehicleInfo;

    @XmlElement(name = "InvoiceInfo", required = true)
    protected InvoiceInfo invoiceInfo;

    public InvoiceInfo getInvoiceInfo() {
        return invoiceInfo;
    }

    public void setInvoiceInfo(InvoiceInfo invoiceInfo) {
        this.invoiceInfo = invoiceInfo;
    }

    public VehicleInfo getVehicleInfo() {
        return vehicleInfo;
    }

    public void setVehicleInfo(VehicleInfo vehicleInfo) {
        this.vehicleInfo = vehicleInfo;
    }

    /**
     * Gets the value of the quoteInfo property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInfo }
     *     
     */
    public QuoteInfo getQuoteInfo() {
        return quoteInfo;
    }

    /**
     * Sets the value of the quoteInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInfo }
     *     
     */
    public void setQuoteInfo(QuoteInfo value) {
        this.quoteInfo = value;
    }

}
