//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dealerName",
    "dealerAddress",
    "dealerLocation",
    "dealerEmail",
    "dealerPhone",
    "invoiceDescription",
    "invoiceTotal",
    "invoiceGrandTotal",
    "taxInfo1",
    "taxInfo2",
    "apt1",
    "apt2"
})
@XmlRootElement(name = "InvoiceInfo")
public class InvoiceInfo {
    @XmlElement(name = "DealerName", required = true)
    protected String dealerName;
    @XmlElement(name = "DealerAddress", required = true)
    protected String dealerAddress;
    @XmlElement(name = "DealerLocation", required = true)
    protected String dealerLocation;
    @XmlElement(name = "DealerEmail", required = true)
    protected String dealerEmail;
    @XmlElement(name = "DealerPhone", required = true)
    protected String dealerPhone;
    @XmlElement(name = "InvoiceDescription", required = true)
    protected String invoiceDescription;
    @XmlElement(name = "InvoiceTotal", required = true)
    protected String invoiceTotal;
    @XmlElement(name = "InvoiceGrandTotal", required = true)
    protected String invoiceGrandTotal;
    @XmlElement(name = "TaxInfo1", required = true)
    protected String taxInfo1;
    @XmlElement(name = "TaxInfo2", required = true)
    protected String taxInfo2;
    @XmlElement(name = "Apt1", required = true)
    protected String apt1;
    @XmlElement(name = "Apt2", required = true)
    protected String apt2;

    public String getApt1() {
        return apt1;
    }

    public void setApt1(String apt1) {
        this.apt1 = apt1;
    }

    public String getApt2() {
        return apt2;
    }

    public void setApt2(String apt2) {
        this.apt2 = apt2;
    }

    public String getInvoiceDescription() {
        return invoiceDescription;
    }

    public void setInvoiceDescription(String invoiceDescription) {
        this.invoiceDescription = invoiceDescription;
    }

    public String getDealerPhone() {
        return dealerPhone;
    }

    public void setDealerPhone(String dealerPhone) {
        this.dealerPhone = dealerPhone;
    }

    public String getTaxInfo1() {
        return taxInfo1;
    }

    public void setTaxInfo1(String taxInfo1) {
        this.taxInfo1 = taxInfo1;
    }

    public String getTaxInfo2() {
        return taxInfo2;
    }

    public void setTaxInfo2(String taxInfo2) {
        this.taxInfo2 = taxInfo2;
    }

    public String getDealerName() {
        return dealerName;
    }

    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    public String getDealerAddress() {
        return dealerAddress;
    }

    public void setDealerAddress(String dealerAddress) {
        this.dealerAddress = dealerAddress;
    }

    public String getDealerLocation() {
        return dealerLocation;
    }

    public void setDealerLocation(String dealerLocation) {
        this.dealerLocation = dealerLocation;
    }

    public String getDealerEmail() {
        return dealerEmail;
    }

    public void setDealerEmail(String dealerEmail) {
        this.dealerEmail = dealerEmail;
    }

    public String getInvoiceTotal() {
        return invoiceTotal;
    }

    public void setInvoiceTotal(String invoiceTotal) {
        this.invoiceTotal = invoiceTotal;
    }

    public String getInvoiceGrandTotal() {
        return invoiceGrandTotal;
    }

    public void setInvoiceGrandTotal(String invoiceGrandTotal) {
        this.invoiceGrandTotal = invoiceGrandTotal;
    }
}
