//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("", "Email");
    private final static QName _FirstName_QNAME = new QName("", "First_name");
    private final static QName _LastName_QNAME = new QName("", "Last_name");
    private final static QName _SecondaryOwnerOrCompany_QNAME = new QName("", "Secondary_owner_or_company");
    private final static QName _DistributorName_QNAME = new QName("", "Distributor_name");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _Address2_QNAME = new QName("", "Address2");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _Province_QNAME = new QName("", "Province");
    private final static QName _PostalCode_QNAME = new QName("", "Postal_code");
    private final static QName _TelHome_QNAME = new QName("", "Tel_home");
    private final static QName _TelWork_QNAME = new QName("", "Tel_work");
    private final static QName _IndianStatusCertificate_QNAME = new QName("", "Indian_status_certificate");
    private final static QName _DriversLicense_QNAME = new QName("", "Drivers_license");
    private final static QName _VehicleID_QNAME = new QName("", "VehicleID");
    private final static QName _VIN_QNAME = new QName("", "VIN");
    private final static QName _Branch_QNAME = new QName("", "Branch");
    private final static QName _Model_QNAME = new QName("", "Model");
    private final static QName _Year_QNAME = new QName("", "Year");
    private final static QName _Price_QNAME = new QName("", "Price");
    private final static QName _Km_QNAME = new QName("", "Km");
    private final static QName _Condition_QNAME = new QName("", "Condition");
    private final static QName _FuelType_QNAME = new QName("", "FuelType");
    private final static QName _Transmission_QNAME = new QName("", "Transmission");
    private final static QName _Cylinders_QNAME = new QName("", "Cylinders");
    private final static QName _EngineSize_QNAME = new QName("", "EngineSize");
    private final static QName _EngineSizeUnit_QNAME = new QName("", "EngineSizeUnit");
    private final static QName _Designation_QNAME = new QName("", "Designation");
    private final static QName _IsTurboEngine_QNAME = new QName("", "IsTurboEngine");
    private final static QName _Is4X4_QNAME = new QName("", "Is4X4");
    private final static QName _IsAllWheelDrive_QNAME = new QName("", "IsAllWheelDrive");
    private final static QName _FullCoverageEndDate_QNAME = new QName("", "FullCoverageEndDate");
    private final static QName _FullCoverageMaxMile_QNAME = new QName("", "FullCoverageMaxMile");
    private final static QName _PowertrainCoverageEndDate_QNAME = new QName("", "PowertrainCoverageEndDate");
    private final static QName _PowertrainCoverageMaxMile_QNAME = new QName("", "PowertrainCoverageMaxMile");
    private final static QName _DeliveryDate_QNAME = new QName("", "DeliveryDate");
    private final static QName _ComponnentName_QNAME = new QName("", "ComponnentName");
    private final static QName _WarrantyID_QNAME = new QName("", "WarrantyID");
    private final static QName _ProgramName_QNAME = new QName("", "ProgramName");
    private final static QName _ProgramOption_QNAME = new QName("", "ProgramOption");
    private final static QName _OptionTerm_QNAME = new QName("", "OptionTerm");
    private final static QName _SalePrice_QNAME = new QName("", "SalePrice");
    private final static QName _FinancingCompany_QNAME = new QName("", "FinancingCompany");
    private final static QName _VehicleDeliveryDate_QNAME = new QName("", "VehicleDeliveryDate");
    private final static QName _SameAsDeliveryDate_QNAME = new QName("", "SameAsDeliveryDate");
    private final static QName _WarrantyStartDate_QNAME = new QName("", "WarrantyStartDate");
    private final static QName _DateOfBirth_QNAME = new QName("", "DateOfBirth");
    private final static QName _Type_QNAME = new QName("", "Type");
    private final static QName _BaseAmount_QNAME = new QName("", "BaseAmount");
    private final static QName _CashDown_QNAME = new QName("", "CashDown");
    private final static QName _Residual_QNAME = new QName("", "Residual");
    private final static QName _PaymentFrequency_QNAME = new QName("", "PaymentFrequency");
    private final static QName _TermMonths_QNAME = new QName("", "TermMonths");
    private final static QName _InterestRate_QNAME = new QName("", "InterestRate");
    private final static QName _ContractNumber_QNAME = new QName("", "ContractNumber");
    private final static QName _SalesRepName_QNAME = new QName("", "SalesRepName");
    private final static QName _DeliveredOn_QNAME = new QName("", "DeliveredOn");
    private final static QName _SignedOn_QNAME = new QName("", "SignedOn");
    private final static QName _SignedLocation_QNAME = new QName("", "SignedLocation");
    private final static QName _DiscountAmount_QNAME = new QName("", "DiscountAmount");
    private final static QName _VehicleMarketValue_QNAME = new QName("", "VehicleMarketValue");
    private final static QName _TransitAmount_QNAME = new QName("", "TransitAmount");
    private final static QName _RDPRMAmount_QNAME = new QName("", "RDPRM_Amount");
    private final static QName _WarrantyAmount_QNAME = new QName("", "WarrantyAmount");
    private final static QName _Accessories_QNAME = new QName("", "Accessories");
    private final static QName _AccessoriesAmount_QNAME = new QName("", "AccessoriesAmount");
    private final static QName _NewTiresDutyAmount_QNAME = new QName("", "NewTiresDutyAmount");
    private final static QName _MaintenanceScheduleAmount_QNAME = new QName("", "MaintenanceScheduleAmount");
    private final static QName _ReplacementInsuranceAmount_QNAME = new QName("", "ReplacementInsuranceAmount");
    private final static QName _ReplacementInsuranceContractNumber_QNAME = new QName("", "ReplacementInsuranceContractNumber");
    private final static QName _LoanInsuranceAmount_QNAME = new QName("", "LoanInsuranceAmount");
    private final static QName _LoanInsuranceContractNumber_QNAME = new QName("", "LoanInsuranceContractNumber");
    private final static QName _DepositAmount_QNAME = new QName("", "DepositAmount");
    private final static QName _OtherClause_QNAME = new QName("", "OtherClause");
    private final static QName _LicensePlateNumber_QNAME = new QName("", "LicensePlateNumber");
    private final static QName _RealKilometers_QNAME = new QName("", "RealKilometers");
    private final static QName _AccommodationSaleContractNumber_QNAME = new QName("", "AccommodationSaleContractNumber");
    private final static QName _TaxRegistration_QNAME = new QName("", "TaxRegistration");
    private final static QName _ValueAmount_QNAME = new QName("", "ValueAmount");
    private final static QName _BalanceAmount_QNAME = new QName("", "BalanceAmount");
    private final static QName _Bank_QNAME = new QName("", "Bank");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VehicleInfo }
     * 
     */
    public VehicleInfo createVehicleInfo() {
        return new VehicleInfo();
    }

    /**
     * Create an instance of {@link ExtraComponents }
     * 
     */
    public ExtraComponents createExtraComponents() {
        return new ExtraComponents();
    }

    /**
     * Create an instance of {@link QuoteSaleContract }
     * 
     */
    public QuoteSaleContract createQuoteSaleContract() {
        return new QuoteSaleContract();
    }

    /**
     * Create an instance of {@link QuoteExchangeVehicle }
     * 
     */
    public QuoteExchangeVehicle createQuoteExchangeVehicle() {
        return new QuoteExchangeVehicle();
    }

    /**
     * Create an instance of {@link QuoteClient }
     * 
     */
    public QuoteClient createQuoteClient() {
        return new QuoteClient();
    }

    /**
     * Create an instance of {@link QuoteVehicle }
     * 
     */
    public QuoteVehicle createQuoteVehicle() {
        return new QuoteVehicle();
    }

    /**
     * Create an instance of {@link QuoteWarranty }
     * 
     */
    public QuoteWarranty createQuoteWarranty() {
        return new QuoteWarranty();
    }

    /**
     * Create an instance of {@link QuoteFinancing }
     * 
     */
    public QuoteFinancing createQuoteFinancing() {
        return new QuoteFinancing();
    }

    /**
     * Create an instance of {@link QuoteSale }
     * 
     */
    public QuoteSale createQuoteSale() {
        return new QuoteSale();
    }

    /**
     * Create an instance of {@link QuoteInfo }
     * 
     */
    public QuoteInfo createQuoteInfo() {
        return new QuoteInfo();
    }

    /**
     * Create an instance of {@link DealerPortal }
     * 
     */
    public DealerPortal createDealerPortal() {
        return new DealerPortal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "First_name")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Last_name")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Secondary_owner_or_company")
    public JAXBElement<String> createSecondaryOwnerOrCompany(String value) {
        return new JAXBElement<String>(_SecondaryOwnerOrCompany_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Distributor_name")
    public JAXBElement<String> createDistributorName(String value) {
        return new JAXBElement<String>(_DistributorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Province")
    public JAXBElement<String> createProvince(String value) {
        return new JAXBElement<String>(_Province_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Postal_code")
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Tel_home")
    public JAXBElement<String> createTelHome(String value) {
        return new JAXBElement<String>(_TelHome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Tel_work")
    public JAXBElement<String> createTelWork(String value) {
        return new JAXBElement<String>(_TelWork_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Indian_status_certificate")
    public JAXBElement<String> createIndianStatusCertificate(String value) {
        return new JAXBElement<String>(_IndianStatusCertificate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Drivers_license")
    public JAXBElement<String> createDriversLicense(String value) {
        return new JAXBElement<String>(_DriversLicense_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VehicleID")
    public JAXBElement<String> createVehicleID(String value) {
        return new JAXBElement<String>(_VehicleID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VIN")
    public JAXBElement<String> createVIN(String value) {
        return new JAXBElement<String>(_VIN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Branch")
    public JAXBElement<String> createBranch(String value) {
        return new JAXBElement<String>(_Branch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Year")
    public JAXBElement<String> createYear(String value) {
        return new JAXBElement<String>(_Year_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Price")
    public JAXBElement<String> createPrice(String value) {
        return new JAXBElement<String>(_Price_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Km")
    public JAXBElement<String> createKm(String value) {
        return new JAXBElement<String>(_Km_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Condition")
    public JAXBElement<String> createCondition(String value) {
        return new JAXBElement<String>(_Condition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "FuelType")
    public JAXBElement<String> createFuelType(String value) {
        return new JAXBElement<String>(_FuelType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Transmission")
    public JAXBElement<String> createTransmission(String value) {
        return new JAXBElement<String>(_Transmission_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Cylinders")
    public JAXBElement<String> createCylinders(String value) {
        return new JAXBElement<String>(_Cylinders_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "EngineSize")
    public JAXBElement<String> createEngineSize(String value) {
        return new JAXBElement<String>(_EngineSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "EngineSizeUnit")
    public JAXBElement<String> createEngineSizeUnit(String value) {
        return new JAXBElement<String>(_EngineSizeUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Designation")
    public JAXBElement<String> createDesignation(String value) {
        return new JAXBElement<String>(_Designation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IsTurboEngine")
    public JAXBElement<String> createIsTurboEngine(String value) {
        return new JAXBElement<String>(_IsTurboEngine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Is4X4")
    public JAXBElement<String> createIs4X4(String value) {
        return new JAXBElement<String>(_Is4X4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IsAllWheelDrive")
    public JAXBElement<String> createIsAllWheelDrive(String value) {
        return new JAXBElement<String>(_IsAllWheelDrive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "FullCoverageEndDate")
    public JAXBElement<String> createFullCoverageEndDate(String value) {
        return new JAXBElement<String>(_FullCoverageEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "FullCoverageMaxMile")
    public JAXBElement<String> createFullCoverageMaxMile(String value) {
        return new JAXBElement<String>(_FullCoverageMaxMile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PowertrainCoverageEndDate")
    public JAXBElement<String> createPowertrainCoverageEndDate(String value) {
        return new JAXBElement<String>(_PowertrainCoverageEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PowertrainCoverageMaxMile")
    public JAXBElement<String> createPowertrainCoverageMaxMile(String value) {
        return new JAXBElement<String>(_PowertrainCoverageMaxMile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DeliveryDate")
    public JAXBElement<String> createDeliveryDate(String value) {
        return new JAXBElement<String>(_DeliveryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ComponnentName")
    public JAXBElement<String> createComponnentName(String value) {
        return new JAXBElement<String>(_ComponnentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "WarrantyID")
    public JAXBElement<String> createWarrantyID(String value) {
        return new JAXBElement<String>(_WarrantyID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ProgramName")
    public JAXBElement<String> createProgramName(String value) {
        return new JAXBElement<String>(_ProgramName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ProgramOption")
    public JAXBElement<String> createProgramOption(String value) {
        return new JAXBElement<String>(_ProgramOption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "OptionTerm")
    public JAXBElement<String> createOptionTerm(String value) {
        return new JAXBElement<String>(_OptionTerm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SalePrice")
    public JAXBElement<String> createSalePrice(String value) {
        return new JAXBElement<String>(_SalePrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "FinancingCompany")
    public JAXBElement<String> createFinancingCompany(String value) {
        return new JAXBElement<String>(_FinancingCompany_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VehicleDeliveryDate")
    public JAXBElement<String> createVehicleDeliveryDate(String value) {
        return new JAXBElement<String>(_VehicleDeliveryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SameAsDeliveryDate")
    public JAXBElement<String> createSameAsDeliveryDate(String value) {
        return new JAXBElement<String>(_SameAsDeliveryDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "WarrantyStartDate")
    public JAXBElement<String> createWarrantyStartDate(String value) {
        return new JAXBElement<String>(_WarrantyStartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DateOfBirth")
    public JAXBElement<String> createDateOfBirth(String value) {
        return new JAXBElement<String>(_DateOfBirth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BaseAmount")
    public JAXBElement<String> createBaseAmount(String value) {
        return new JAXBElement<String>(_BaseAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "CashDown")
    public JAXBElement<String> createCashDown(String value) {
        return new JAXBElement<String>(_CashDown_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Residual")
    public JAXBElement<String> createResidual(String value) {
        return new JAXBElement<String>(_Residual_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PaymentFrequency")
    public JAXBElement<String> createPaymentFrequency(String value) {
        return new JAXBElement<String>(_PaymentFrequency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "TermMonths")
    public JAXBElement<String> createTermMonths(String value) {
        return new JAXBElement<String>(_TermMonths_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "InterestRate")
    public JAXBElement<String> createInterestRate(String value) {
        return new JAXBElement<String>(_InterestRate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ContractNumber")
    public JAXBElement<String> createContractNumber(String value) {
        return new JAXBElement<String>(_ContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SalesRepName")
    public JAXBElement<String> createSalesRepName(String value) {
        return new JAXBElement<String>(_SalesRepName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DeliveredOn")
    public JAXBElement<String> createDeliveredOn(String value) {
        return new JAXBElement<String>(_DeliveredOn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SignedOn")
    public JAXBElement<String> createSignedOn(String value) {
        return new JAXBElement<String>(_SignedOn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SignedLocation")
    public JAXBElement<String> createSignedLocation(String value) {
        return new JAXBElement<String>(_SignedLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DiscountAmount")
    public JAXBElement<String> createDiscountAmount(String value) {
        return new JAXBElement<String>(_DiscountAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "VehicleMarketValue")
    public JAXBElement<String> createVehicleMarketValue(String value) {
        return new JAXBElement<String>(_VehicleMarketValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "TransitAmount")
    public JAXBElement<String> createTransitAmount(String value) {
        return new JAXBElement<String>(_TransitAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "RDPRM_Amount")
    public JAXBElement<String> createRDPRMAmount(String value) {
        return new JAXBElement<String>(_RDPRMAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "WarrantyAmount")
    public JAXBElement<String> createWarrantyAmount(String value) {
        return new JAXBElement<String>(_WarrantyAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Accessories")
    public JAXBElement<String> createAccessories(String value) {
        return new JAXBElement<String>(_Accessories_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "AccessoriesAmount")
    public JAXBElement<String> createAccessoriesAmount(String value) {
        return new JAXBElement<String>(_AccessoriesAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "NewTiresDutyAmount")
    public JAXBElement<String> createNewTiresDutyAmount(String value) {
        return new JAXBElement<String>(_NewTiresDutyAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MaintenanceScheduleAmount")
    public JAXBElement<String> createMaintenanceScheduleAmount(String value) {
        return new JAXBElement<String>(_MaintenanceScheduleAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReplacementInsuranceAmount")
    public JAXBElement<String> createReplacementInsuranceAmount(String value) {
        return new JAXBElement<String>(_ReplacementInsuranceAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReplacementInsuranceContractNumber")
    public JAXBElement<String> createReplacementInsuranceContractNumber(String value) {
        return new JAXBElement<String>(_ReplacementInsuranceContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "LoanInsuranceAmount")
    public JAXBElement<String> createLoanInsuranceAmount(String value) {
        return new JAXBElement<String>(_LoanInsuranceAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "LoanInsuranceContractNumber")
    public JAXBElement<String> createLoanInsuranceContractNumber(String value) {
        return new JAXBElement<String>(_LoanInsuranceContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DepositAmount")
    public JAXBElement<String> createDepositAmount(String value) {
        return new JAXBElement<String>(_DepositAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "OtherClause")
    public JAXBElement<String> createOtherClause(String value) {
        return new JAXBElement<String>(_OtherClause_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "LicensePlateNumber")
    public JAXBElement<String> createLicensePlateNumber(String value) {
        return new JAXBElement<String>(_LicensePlateNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "RealKilometers")
    public JAXBElement<String> createRealKilometers(String value) {
        return new JAXBElement<String>(_RealKilometers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "AccommodationSaleContractNumber")
    public JAXBElement<String> createAccommodationSaleContractNumber(String value) {
        return new JAXBElement<String>(_AccommodationSaleContractNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "TaxRegistration")
    public JAXBElement<String> createTaxRegistration(String value) {
        return new JAXBElement<String>(_TaxRegistration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ValueAmount")
    public JAXBElement<String> createValueAmount(String value) {
        return new JAXBElement<String>(_ValueAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BalanceAmount")
    public JAXBElement<String> createBalanceAmount(String value) {
        return new JAXBElement<String>(_BalanceAmount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Bank")
    public JAXBElement<String> createBank(String value) {
        return new JAXBElement<String>(_Bank_QNAME, String.class, null, value);
    }

}
