//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ContractNumber"/&gt;
 *         &lt;element ref="{}SalesRepName"/&gt;
 *         &lt;element ref="{}DeliveredOn"/&gt;
 *         &lt;element ref="{}SignedOn"/&gt;
 *         &lt;element ref="{}SignedLocation"/&gt;
 *         &lt;element ref="{}DiscountAmount"/&gt;
 *         &lt;element ref="{}VehicleMarketValue"/&gt;
 *         &lt;element ref="{}TransitAmount"/&gt;
 *         &lt;element ref="{}RDPRM_Amount"/&gt;
 *         &lt;element ref="{}WarrantyAmount"/&gt;
 *         &lt;element ref="{}Accessories"/&gt;
 *         &lt;element ref="{}AccessoriesAmount"/&gt;
 *         &lt;element ref="{}NewTiresDutyAmount"/&gt;
 *         &lt;element ref="{}MaintenanceScheduleAmount"/&gt;
 *         &lt;element ref="{}ReplacementInsuranceAmount"/&gt;
 *         &lt;element ref="{}ReplacementInsuranceContractNumber"/&gt;
 *         &lt;element ref="{}LoanInsuranceAmount"/&gt;
 *         &lt;element ref="{}LoanInsuranceContractNumber"/&gt;
 *         &lt;element ref="{}DepositAmount"/&gt;
 *         &lt;element ref="{}OtherClause"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contractNumber",
    "salesRepName",
    "deliveredOn",
    "signedOn",
    "signedLocation",
    "discountAmount",
    "vehicleMarketValue",
    "transitAmount",
    "rdprmAmount",
    "warrantyAmount",
    "accessories",
    "accessoriesAmount",
    "newTiresDutyAmount",
    "maintenanceScheduleAmount",
    "replacementInsuranceAmount",
    "replacementInsuranceContractNumber",
    "loanInsuranceAmount",
    "loanInsuranceContractNumber",
    "depositAmount",
    "otherClause"
})
@XmlRootElement(name = "QuoteSaleContract")
public class QuoteSaleContract {

    @XmlElement(name = "ContractNumber", required = true)
    protected String contractNumber;
    @XmlElement(name = "SalesRepName", required = true)
    protected String salesRepName;
    @XmlElement(name = "DeliveredOn", required = true)
    protected String deliveredOn;
    @XmlElement(name = "SignedOn", required = true)
    protected String signedOn;
    @XmlElement(name = "SignedLocation", required = true)
    protected String signedLocation;
    @XmlElement(name = "DiscountAmount", required = true)
    protected String discountAmount;
    @XmlElement(name = "VehicleMarketValue", required = true)
    protected String vehicleMarketValue;
    @XmlElement(name = "TransitAmount", required = true)
    protected String transitAmount;
    @XmlElement(name = "RDPRM_Amount", required = true)
    protected String rdprmAmount;
    @XmlElement(name = "WarrantyAmount", required = true)
    protected String warrantyAmount;
    @XmlElement(name = "Accessories", required = true)
    protected String accessories;
    @XmlElement(name = "AccessoriesAmount", required = true)
    protected String accessoriesAmount;
    @XmlElement(name = "NewTiresDutyAmount", required = true)
    protected String newTiresDutyAmount;
    @XmlElement(name = "MaintenanceScheduleAmount", required = true)
    protected String maintenanceScheduleAmount;
    @XmlElement(name = "ReplacementInsuranceAmount", required = true)
    protected String replacementInsuranceAmount;
    @XmlElement(name = "ReplacementInsuranceContractNumber", required = true)
    protected String replacementInsuranceContractNumber;
    @XmlElement(name = "LoanInsuranceAmount", required = true)
    protected String loanInsuranceAmount;
    @XmlElement(name = "LoanInsuranceContractNumber", required = true)
    protected String loanInsuranceContractNumber;
    @XmlElement(name = "DepositAmount", required = true)
    protected String depositAmount;
    @XmlElement(name = "OtherClause", required = true)
    protected String otherClause;

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the salesRepName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesRepName() {
        return salesRepName;
    }

    /**
     * Sets the value of the salesRepName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesRepName(String value) {
        this.salesRepName = value;
    }

    /**
     * Gets the value of the deliveredOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveredOn() {
        return deliveredOn;
    }

    /**
     * Sets the value of the deliveredOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveredOn(String value) {
        this.deliveredOn = value;
    }

    /**
     * Gets the value of the signedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedOn() {
        return signedOn;
    }

    /**
     * Sets the value of the signedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedOn(String value) {
        this.signedOn = value;
    }

    /**
     * Gets the value of the signedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedLocation() {
        return signedLocation;
    }

    /**
     * Sets the value of the signedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedLocation(String value) {
        this.signedLocation = value;
    }

    /**
     * Gets the value of the discountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountAmount() {
        return discountAmount;
    }

    /**
     * Sets the value of the discountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountAmount(String value) {
        this.discountAmount = value;
    }

    /**
     * Gets the value of the vehicleMarketValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMarketValue() {
        return vehicleMarketValue;
    }

    /**
     * Sets the value of the vehicleMarketValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMarketValue(String value) {
        this.vehicleMarketValue = value;
    }

    /**
     * Gets the value of the transitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransitAmount() {
        return transitAmount;
    }

    /**
     * Sets the value of the transitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransitAmount(String value) {
        this.transitAmount = value;
    }

    /**
     * Gets the value of the rdprmAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRDPRMAmount() {
        return rdprmAmount;
    }

    /**
     * Sets the value of the rdprmAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRDPRMAmount(String value) {
        this.rdprmAmount = value;
    }

    /**
     * Gets the value of the warrantyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyAmount() {
        return warrantyAmount;
    }

    /**
     * Sets the value of the warrantyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyAmount(String value) {
        this.warrantyAmount = value;
    }

    /**
     * Gets the value of the accessories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessories() {
        return accessories;
    }

    /**
     * Sets the value of the accessories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessories(String value) {
        this.accessories = value;
    }

    /**
     * Gets the value of the accessoriesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessoriesAmount() {
        return accessoriesAmount;
    }

    /**
     * Sets the value of the accessoriesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessoriesAmount(String value) {
        this.accessoriesAmount = value;
    }

    /**
     * Gets the value of the newTiresDutyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewTiresDutyAmount() {
        return newTiresDutyAmount;
    }

    /**
     * Sets the value of the newTiresDutyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewTiresDutyAmount(String value) {
        this.newTiresDutyAmount = value;
    }

    /**
     * Gets the value of the maintenanceScheduleAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceScheduleAmount() {
        return maintenanceScheduleAmount;
    }

    /**
     * Sets the value of the maintenanceScheduleAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceScheduleAmount(String value) {
        this.maintenanceScheduleAmount = value;
    }

    /**
     * Gets the value of the replacementInsuranceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacementInsuranceAmount() {
        return replacementInsuranceAmount;
    }

    /**
     * Sets the value of the replacementInsuranceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacementInsuranceAmount(String value) {
        this.replacementInsuranceAmount = value;
    }

    /**
     * Gets the value of the replacementInsuranceContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplacementInsuranceContractNumber() {
        return replacementInsuranceContractNumber;
    }

    /**
     * Sets the value of the replacementInsuranceContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplacementInsuranceContractNumber(String value) {
        this.replacementInsuranceContractNumber = value;
    }

    /**
     * Gets the value of the loanInsuranceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanInsuranceAmount() {
        return loanInsuranceAmount;
    }

    /**
     * Sets the value of the loanInsuranceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanInsuranceAmount(String value) {
        this.loanInsuranceAmount = value;
    }

    /**
     * Gets the value of the loanInsuranceContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanInsuranceContractNumber() {
        return loanInsuranceContractNumber;
    }

    /**
     * Sets the value of the loanInsuranceContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanInsuranceContractNumber(String value) {
        this.loanInsuranceContractNumber = value;
    }

    /**
     * Gets the value of the depositAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositAmount() {
        return depositAmount;
    }

    /**
     * Sets the value of the depositAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositAmount(String value) {
        this.depositAmount = value;
    }

    /**
     * Gets the value of the otherClause property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherClause() {
        return otherClause;
    }

    /**
     * Sets the value of the otherClause property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherClause(String value) {
        this.otherClause = value;
    }

}
