//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}QuoteSaleContract"/&gt;
 *         &lt;element ref="{}QuoteExchangeVehicle"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quoteSaleContract",
    "quoteExchangeVehicle"
})
@XmlRootElement(name = "QuoteSale")
public class QuoteSale {

    @XmlElement(name = "QuoteSaleContract", required = true)
    protected QuoteSaleContract quoteSaleContract;
    @XmlElement(name = "QuoteExchangeVehicle", required = true)
    protected QuoteExchangeVehicle quoteExchangeVehicle;

    /**
     * Gets the value of the quoteSaleContract property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteSaleContract }
     *     
     */
    public QuoteSaleContract getQuoteSaleContract() {
        return quoteSaleContract;
    }

    /**
     * Sets the value of the quoteSaleContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteSaleContract }
     *     
     */
    public void setQuoteSaleContract(QuoteSaleContract value) {
        this.quoteSaleContract = value;
    }

    /**
     * Gets the value of the quoteExchangeVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteExchangeVehicle }
     *     
     */
    public QuoteExchangeVehicle getQuoteExchangeVehicle() {
        return quoteExchangeVehicle;
    }

    /**
     * Sets the value of the quoteExchangeVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteExchangeVehicle }
     *     
     */
    public void setQuoteExchangeVehicle(QuoteExchangeVehicle value) {
        this.quoteExchangeVehicle = value;
    }

}
