//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}DateOfBirth"/&gt;
 *         &lt;element ref="{}Type"/&gt;
 *         &lt;element ref="{}BaseAmount"/&gt;
 *         &lt;element ref="{}CashDown"/&gt;
 *         &lt;element ref="{}Residual"/&gt;
 *         &lt;element ref="{}PaymentFrequency"/&gt;
 *         &lt;element ref="{}TermMonths"/&gt;
 *         &lt;element ref="{}InterestRate"/&gt;
 *         &lt;element ref="{}FinancingCompany"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateOfBirth",
    "type",
    "baseAmount",
    "cashDown",
    "residual",
    "paymentFrequency",
    "termMonths",
    "interestRate",
    "financingCompany"
})
@XmlRootElement(name = "QuoteFinancing")
public class QuoteFinancing {

    @XmlElement(name = "DateOfBirth", required = true)
    protected String dateOfBirth;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "BaseAmount", required = true)
    protected String baseAmount;
    @XmlElement(name = "CashDown", required = true)
    protected String cashDown;
    @XmlElement(name = "Residual", required = true)
    protected String residual;
    @XmlElement(name = "PaymentFrequency", required = true)
    protected String paymentFrequency;
    @XmlElement(name = "TermMonths", required = true)
    protected String termMonths;
    @XmlElement(name = "InterestRate", required = true)
    protected String interestRate;
    @XmlElement(name = "FinancingCompany", required = true)
    protected String financingCompany;

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the baseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseAmount() {
        return baseAmount;
    }

    /**
     * Sets the value of the baseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseAmount(String value) {
        this.baseAmount = value;
    }

    /**
     * Gets the value of the cashDown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashDown() {
        return cashDown;
    }

    /**
     * Sets the value of the cashDown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashDown(String value) {
        this.cashDown = value;
    }

    /**
     * Gets the value of the residual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidual() {
        return residual;
    }

    /**
     * Sets the value of the residual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidual(String value) {
        this.residual = value;
    }

    /**
     * Gets the value of the paymentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    /**
     * Sets the value of the paymentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFrequency(String value) {
        this.paymentFrequency = value;
    }

    /**
     * Gets the value of the termMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermMonths() {
        return termMonths;
    }

    /**
     * Sets the value of the termMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermMonths(String value) {
        this.termMonths = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestRate(String value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the financingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancingCompany() {
        return financingCompany;
    }

    /**
     * Sets the value of the financingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancingCompany(String value) {
        this.financingCompany = value;
    }

}
