//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}QuoteClient"/&gt;
 *         &lt;element ref="{}QuoteVehicle"/&gt;
 *         &lt;element ref="{}QuoteWarranty"/&gt;
 *         &lt;element ref="{}QuoteFinancing"/&gt;
 *         &lt;element ref="{}QuoteSale"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quoteClient",
    "quoteVehicle",
    "quoteWarranty",
    "quoteFinancing",
    "quoteSale"
})
@XmlRootElement(name = "QuoteInfo")
public class QuoteInfo {

    @XmlElement(name = "QuoteClient", required = true)
    protected QuoteClient quoteClient;
    @XmlElement(name = "QuoteVehicle", required = true)
    protected QuoteVehicle quoteVehicle;
    @XmlElement(name = "QuoteWarranty", required = true)
    protected QuoteWarranty quoteWarranty;
    @XmlElement(name = "QuoteFinancing", required = true)
    protected QuoteFinancing quoteFinancing;
    @XmlElement(name = "QuoteSale", required = true)
    protected QuoteSale quoteSale;

    /**
     * Gets the value of the quoteClient property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteClient }
     *     
     */
    public QuoteClient getQuoteClient() {
        return quoteClient;
    }

    /**
     * Sets the value of the quoteClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteClient }
     *     
     */
    public void setQuoteClient(QuoteClient value) {
        this.quoteClient = value;
    }

    /**
     * Gets the value of the quoteVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteVehicle }
     *     
     */
    public QuoteVehicle getQuoteVehicle() {
        return quoteVehicle;
    }

    /**
     * Sets the value of the quoteVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteVehicle }
     *     
     */
    public void setQuoteVehicle(QuoteVehicle value) {
        this.quoteVehicle = value;
    }

    /**
     * Gets the value of the quoteWarranty property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteWarranty }
     *     
     */
    public QuoteWarranty getQuoteWarranty() {
        return quoteWarranty;
    }

    /**
     * Sets the value of the quoteWarranty property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteWarranty }
     *     
     */
    public void setQuoteWarranty(QuoteWarranty value) {
        this.quoteWarranty = value;
    }

    /**
     * Gets the value of the quoteFinancing property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteFinancing }
     *     
     */
    public QuoteFinancing getQuoteFinancing() {
        return quoteFinancing;
    }

    /**
     * Sets the value of the quoteFinancing property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteFinancing }
     *     
     */
    public void setQuoteFinancing(QuoteFinancing value) {
        this.quoteFinancing = value;
    }

    /**
     * Gets the value of the quoteSale property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteSale }
     *     
     */
    public QuoteSale getQuoteSale() {
        return quoteSale;
    }

    /**
     * Sets the value of the quoteSale property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteSale }
     *     
     */
    public void setQuoteSale(QuoteSale value) {
        this.quoteSale = value;
    }

}
