//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}VIN"/&gt;
 *         &lt;element ref="{}Branch"/&gt;
 *         &lt;element ref="{}Model"/&gt;
 *         &lt;element ref="{}Year"/&gt;
 *         &lt;element ref="{}Cylinders"/&gt;
 *         &lt;element ref="{}LicensePlateNumber"/&gt;
 *         &lt;element ref="{}Km"/&gt;
 *         &lt;element ref="{}RealKilometers"/&gt;
 *         &lt;element ref="{}AccommodationSaleContractNumber"/&gt;
 *         &lt;element ref="{}TaxRegistration"/&gt;
 *         &lt;element ref="{}ValueAmount"/&gt;
 *         &lt;element ref="{}BalanceAmount"/&gt;
 *         &lt;element ref="{}Bank"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vin",
    "branch",
    "model",
    "year",
    "cylinders",
    "licensePlateNumber",
    "km",
    "realKilometers",
    "isAccommodationSale",
    "accommodationSaleContractNumber",
    "taxRegistration",
    "valueAmount",
    "balanceAmount",
    "bank"
})
@XmlRootElement(name = "QuoteExchangeVehicle")
public class QuoteExchangeVehicle {

    @XmlElement(name = "VIN", required = true)
    protected String vin;
    @XmlElement(name = "Branch", required = true)
    protected String branch;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Year", required = true)
    protected String year;
    @XmlElement(name = "Cylinders", required = true)
    protected String cylinders;
    @XmlElement(name = "LicensePlateNumber", required = true)
    protected String licensePlateNumber;
    @XmlElement(name = "Km", required = true)
    protected String km;
    @XmlElement(name = "RealKilometers", required = true)
    protected String realKilometers;

    public String getIsAccommodationSale() {
        return isAccommodationSale;
    }

    public void setIsAccommodationSale(String isAccommodationSale) {
        this.isAccommodationSale = isAccommodationSale;
    }

    @XmlElement(name = "IsAccommodationSale", required = true)
    protected String isAccommodationSale;
    @XmlElement(name = "AccommodationSaleContractNumber", required = true)
    protected String accommodationSaleContractNumber;
    @XmlElement(name = "TaxRegistration", required = true)
    protected String taxRegistration;
    @XmlElement(name = "ValueAmount", required = true)
    protected String valueAmount;
    @XmlElement(name = "BalanceAmount", required = true)
    protected String balanceAmount;
    @XmlElement(name = "Bank", required = true)
    protected String bank;

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIN() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIN(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the cylinders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCylinders() {
        return cylinders;
    }

    /**
     * Sets the value of the cylinders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCylinders(String value) {
        this.cylinders = value;
    }

    /**
     * Gets the value of the licensePlateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicensePlateNumber() {
        return licensePlateNumber;
    }

    /**
     * Sets the value of the licensePlateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicensePlateNumber(String value) {
        this.licensePlateNumber = value;
    }

    /**
     * Gets the value of the km property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKm() {
        return km;
    }

    /**
     * Sets the value of the km property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKm(String value) {
        this.km = value;
    }

    /**
     * Gets the value of the realKilometers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealKilometers() {
        return realKilometers;
    }

    /**
     * Sets the value of the realKilometers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealKilometers(String value) {
        this.realKilometers = value;
    }

    /**
     * Gets the value of the accommodationSaleContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccommodationSaleContractNumber() {
        return accommodationSaleContractNumber;
    }

    /**
     * Sets the value of the accommodationSaleContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccommodationSaleContractNumber(String value) {
        this.accommodationSaleContractNumber = value;
    }

    /**
     * Gets the value of the taxRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRegistration() {
        return taxRegistration;
    }

    /**
     * Sets the value of the taxRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRegistration(String value) {
        this.taxRegistration = value;
    }

    /**
     * Gets the value of the valueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueAmount() {
        return valueAmount;
    }

    /**
     * Sets the value of the valueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueAmount(String value) {
        this.valueAmount = value;
    }

    /**
     * Gets the value of the balanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * Sets the value of the balanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceAmount(String value) {
        this.balanceAmount = value;
    }

    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBank(String value) {
        this.bank = value;
    }

}
