//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Email"/&gt;
 *         &lt;element ref="{}First_name"/&gt;
 *         &lt;element ref="{}Last_name"/&gt;
 *         &lt;element ref="{}Secondary_owner_or_company"/&gt;
 *         &lt;element ref="{}Distributor_name"/&gt;
 *         &lt;element ref="{}Address"/&gt;
 *         &lt;element ref="{}Address2"/&gt;
 *         &lt;element ref="{}City"/&gt;
 *         &lt;element ref="{}Province"/&gt;
 *         &lt;element ref="{}Postal_code"/&gt;
 *         &lt;element ref="{}Tel_home"/&gt;
 *         &lt;element ref="{}Tel_work"/&gt;
 *         &lt;element ref="{}Indian_status_certificate"/&gt;
 *         &lt;element ref="{}Drivers_license"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "email",
    "firstName",
    "lastName",
    "secondaryOwnerOrCompany",
    "distributorName",
    "address",
    "address2",
    "city",
    "province",
    "postalCode",
    "telHome",
    "telWork",
    "indianStatusCertificate",
    "driversLicense"
})
@XmlRootElement(name = "QuoteClient")
public class QuoteClient {

    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "First_name", required = true)
    protected String firstName;
    @XmlElement(name = "Last_name", required = true)
    protected String lastName;
    @XmlElement(name = "Secondary_owner_or_company", required = true)
    protected String secondaryOwnerOrCompany;
    @XmlElement(name = "Distributor_name", required = true)
    protected String distributorName;
    @XmlElement(name = "Address", required = true)
    protected String address;
    @XmlElement(name = "Address2", required = true)
    protected String address2;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "Province", required = true)
    protected String province;
    @XmlElement(name = "Postal_code", required = true)
    protected String postalCode;
    @XmlElement(name = "Tel_home", required = true)
    protected String telHome;
    @XmlElement(name = "Tel_work", required = true)
    protected String telWork;
    @XmlElement(name = "Indian_status_certificate", required = true)
    protected String indianStatusCertificate;
    @XmlElement(name = "Drivers_license", required = true)
    protected String driversLicense;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the secondaryOwnerOrCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryOwnerOrCompany() {
        return secondaryOwnerOrCompany;
    }

    /**
     * Sets the value of the secondaryOwnerOrCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryOwnerOrCompany(String value) {
        this.secondaryOwnerOrCompany = value;
    }

    /**
     * Gets the value of the distributorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributorName() {
        return distributorName;
    }

    /**
     * Sets the value of the distributorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributorName(String value) {
        this.distributorName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the telHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelHome() {
        return telHome;
    }

    /**
     * Sets the value of the telHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelHome(String value) {
        this.telHome = value;
    }

    /**
     * Gets the value of the telWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelWork() {
        return telWork;
    }

    /**
     * Sets the value of the telWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelWork(String value) {
        this.telWork = value;
    }

    /**
     * Gets the value of the indianStatusCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndianStatusCertificate() {
        return indianStatusCertificate;
    }

    /**
     * Sets the value of the indianStatusCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndianStatusCertificate(String value) {
        this.indianStatusCertificate = value;
    }

    /**
     * Gets the value of the driversLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicense() {
        return driversLicense;
    }

    /**
     * Sets the value of the driversLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicense(String value) {
        this.driversLicense = value;
    }

}
