//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}WarrantyID"/&gt;
 *         &lt;element ref="{}ProgramName"/&gt;
 *         &lt;element ref="{}ProgramOption"/&gt;
 *         &lt;element ref="{}OptionTerm"/&gt;
 *         &lt;element ref="{}ExtraComponents"/&gt;
 *         &lt;element ref="{}SalePrice"/&gt;
 *         &lt;element ref="{}FinancingCompany"/&gt;
 *         &lt;element ref="{}VehicleDeliveryDate"/&gt;
 *         &lt;element ref="{}SameAsDeliveryDate"/&gt;
 *         &lt;element ref="{}WarrantyStartDate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "warrantyID",
    "programName",
    "programOption",
    "programDescription",
    "optionTerm",
    "optionTermMonth",
    "optionTermKm",
    "optionTermPrice",
    "optionTermAmountPerVisit",
    "optionTermAmountTotal",
    "optionTermAmountText",
    "extraComponents",
    "salePrice",
    "financingCompany",
    "vehicleDeliveryDate",
    "sameAsDeliveryDate",
    "warrantyStartDate"
})
@XmlRootElement(name = "QuoteWarranty")
public class QuoteWarranty {

    @XmlElement(name = "WarrantyID", required = true)
    protected String warrantyID;
    @XmlElement(name = "ProgramName", required = true)
    protected String programName;
    @XmlElement(name = "ProgramOption", required = true)
    protected String programOption;
    @XmlElement(name = "ProgramDescription", required = true)
    protected String programDescription;
    @XmlElement(name = "OptionTerm", required = true)
    protected String optionTerm;
    @XmlElement(name = "OptionTermMonth", required = true)
    protected String optionTermMonth;
    @XmlElement(name = "OptionTermKm", required = true)
    protected String optionTermKm;
    @XmlElement(name = "OptionTermPrice", required = true)
    protected String optionTermPrice;
    @XmlElement(name = "OptionTermAmountPerVisit", required = true)
    protected String optionTermAmountPerVisit;
    @XmlElement(name = "OptionTermAmountTotal", required = true)
    protected String optionTermAmountTotal;

    public String getOptionTermAmountText() {
        return optionTermAmountText;
    }

    public void setOptionTermAmountText(String optionTermAmountText) {
        this.optionTermAmountText = optionTermAmountText;
    }

    @XmlElement(name = "OptionTermAmountText", required = true)
    protected String optionTermAmountText;
    @XmlElement(name = "ExtraComponents", required = true)
    protected ExtraComponents extraComponents;
    @XmlElement(name = "SalePrice", required = true)
    protected String salePrice;

    public String getOptionTermAmountPerVisit() {
        return optionTermAmountPerVisit;
    }

    public void setOptionTermAmountPerVisit(String optionTermAmountPerVisit) {
        this.optionTermAmountPerVisit = optionTermAmountPerVisit;
    }

    public String getOptionTermAmountTotal() {
        return optionTermAmountTotal;
    }

    public void setOptionTermAmountTotal(String optionTermAmountTotal) {
        this.optionTermAmountTotal = optionTermAmountTotal;
    }

    public String getProgramDescription() {
        return programDescription;
    }

    public String getOptionTermPrice() {
        return optionTermPrice;
    }

    public void setOptionTermPrice(String optionTermPrice) {
        this.optionTermPrice = optionTermPrice;
    }

    public void setProgramDescription(String programDescription) {
        this.programDescription = programDescription;
    }

    @XmlElement(name = "FinancingCompany", required = true)
    protected String financingCompany;
    @XmlElement(name = "VehicleDeliveryDate", required = true)
    protected String vehicleDeliveryDate;
    @XmlElement(name = "SameAsDeliveryDate", required = true)
    protected String sameAsDeliveryDate;
    @XmlElement(name = "WarrantyStartDate", required = true)
    protected String warrantyStartDate;

    public String getOptionTermMonth() {
        return optionTermMonth;
    }

    public void setOptionTermMonth(String optionTermMonth) {
        this.optionTermMonth = optionTermMonth;
    }

    public String getOptionTermKm() {
        return optionTermKm;
    }

    public void setOptionTermKm(String optionTermKm) {
        this.optionTermKm = optionTermKm;
    }

    /**
     * Gets the value of the warrantyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyID() {
        return warrantyID;
    }

    /**
     * Sets the value of the warrantyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyID(String value) {
        this.warrantyID = value;
    }

    /**
     * Gets the value of the programName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * Sets the value of the programName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramName(String value) {
        this.programName = value;
    }

    /**
     * Gets the value of the programOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramOption() {
        return programOption;
    }

    /**
     * Sets the value of the programOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramOption(String value) {
        this.programOption = value;
    }

    /**
     * Gets the value of the optionTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionTerm() {
        return optionTerm;
    }

    /**
     * Sets the value of the optionTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionTerm(String value) {
        this.optionTerm = value;
    }

    /**
     * Gets the value of the extraComponents property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraComponents }
     *     
     */
    public ExtraComponents getExtraComponents() {
        return extraComponents;
    }

    /**
     * Sets the value of the extraComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraComponents }
     *     
     */
    public void setExtraComponents(ExtraComponents value) {
        this.extraComponents = value;
    }

    /**
     * Gets the value of the salePrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalePrice() {
        return salePrice;
    }

    /**
     * Sets the value of the salePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalePrice(String value) {
        this.salePrice = value;
    }

    /**
     * Gets the value of the financingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancingCompany() {
        return financingCompany;
    }

    /**
     * Sets the value of the financingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancingCompany(String value) {
        this.financingCompany = value;
    }

    /**
     * Gets the value of the vehicleDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleDeliveryDate() {
        return vehicleDeliveryDate;
    }

    /**
     * Sets the value of the vehicleDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleDeliveryDate(String value) {
        this.vehicleDeliveryDate = value;
    }

    /**
     * Gets the value of the sameAsDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSameAsDeliveryDate() {
        return sameAsDeliveryDate;
    }

    /**
     * Sets the value of the sameAsDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSameAsDeliveryDate(String value) {
        this.sameAsDeliveryDate = value;
    }

    /**
     * Gets the value of the warrantyStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyStartDate() {
        return warrantyStartDate;
    }

    /**
     * Sets the value of the warrantyStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyStartDate(String value) {
        this.warrantyStartDate = value;
    }

}
