//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.10 at 02:38:35 PM ICT 
//


package ProjectContext.BusinessObject.Dealer;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}VehicleID"/&gt;
 *         &lt;element ref="{}VIN"/&gt;
 *         &lt;element ref="{}Branch"/&gt;
 *         &lt;element ref="{}Model"/&gt;
 *         &lt;element ref="{}Year"/&gt;
 *         &lt;element ref="{}Price"/&gt;
 *         &lt;element ref="{}Km"/&gt;
 *         &lt;element ref="{}Condition"/&gt;
 *         &lt;element ref="{}FuelType"/&gt;
 *         &lt;element ref="{}Transmission"/&gt;
 *         &lt;element ref="{}Cylinders"/&gt;
 *         &lt;element ref="{}EngineSize"/&gt;
 *         &lt;element ref="{}EngineSizeUnit"/&gt;
 *         &lt;element ref="{}Designation"/&gt;
 *         &lt;element ref="{}IsTurboEngine"/&gt;
 *         &lt;element ref="{}Is4X4"/&gt;
 *         &lt;element ref="{}IsAllWheelDrive"/&gt;
 *         &lt;element ref="{}FullCoverageEndDate"/&gt;
 *         &lt;element ref="{}FullCoverageMaxMile"/&gt;
 *         &lt;element ref="{}PowertrainCoverageEndDate"/&gt;
 *         &lt;element ref="{}PowertrainCoverageMaxMile"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleType",
    "vehicleID",
    "vin",
    "branch",
    "model",
    "year",
    "price",
    "km",
    "condition",
    "fuelType",
    "transmission",
    "cylinders",
    "engineSize",
    "engineSizeUnit",
    "designation",
    "isTurboEngine",
    "is4X4",
    "isAllWheelDrive",
    "fullCoverageEndDate",
    "fullCoverageMaxMile",
    "powertrainCoverageEndDate",
    "powertrainCoverageMaxMile"
})
@XmlRootElement(name = "VehicleInfo")
public class VehicleInfo {
    @XmlElement(name = "VehicleType", required = true)
    protected String vehicleType;
    @XmlElement(name = "VehicleID", required = true)
    protected String vehicleID;
    @XmlElement(name = "VIN", required = true)
    protected String vin;
    @XmlElement(name = "Branch", required = true)
    protected String branch;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Year", required = true)
    protected String year;
    @XmlElement(name = "Price", required = true)
    protected String price;
    @XmlElement(name = "Km", required = true)
    protected String km;
    @XmlElement(name = "Condition", required = true)
    protected String condition;
    @XmlElement(name = "FuelType", required = true)
    protected String fuelType;
    @XmlElement(name = "Transmission", required = true)
    protected String transmission;
    @XmlElement(name = "Cylinders", required = true)
    protected String cylinders;
    @XmlElement(name = "EngineSize", required = true)
    protected String engineSize;
    @XmlElement(name = "EngineSizeUnit", required = true)
    protected String engineSizeUnit;
    @XmlElement(name = "Designation", required = true)
    protected String designation;
    @XmlElement(name = "IsTurboEngine", required = true)
    protected String isTurboEngine;
    @XmlElement(name = "Is4X4", required = true)
    protected String is4X4;
    @XmlElement(name = "IsAllWheelDrive", required = true)
    protected String isAllWheelDrive;
    @XmlElement(name = "FullCoverageEndDate", required = true)
    protected String fullCoverageEndDate;
    @XmlElement(name = "FullCoverageMaxMile", required = true)
    protected String fullCoverageMaxMile;
    @XmlElement(name = "PowertrainCoverageEndDate", required = true)
    protected String powertrainCoverageEndDate;
    @XmlElement(name = "PowertrainCoverageMaxMile", required = true)
    protected String powertrainCoverageMaxMile;

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    /**
     * Gets the value of the vehicleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleID() {
        return vehicleID;
    }

    /**
     * Sets the value of the vehicleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleID(String value) {
        this.vehicleID = value;
    }

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIN() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIN(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranch() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranch(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the km property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKm() {
        return km;
    }

    /**
     * Sets the value of the km property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKm(String value) {
        this.km = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelType(String value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmission(String value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the cylinders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCylinders() {
        return cylinders;
    }

    /**
     * Sets the value of the cylinders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCylinders(String value) {
        this.cylinders = value;
    }

    /**
     * Gets the value of the engineSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineSize() {
        return engineSize;
    }

    /**
     * Sets the value of the engineSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineSize(String value) {
        this.engineSize = value;
    }

    /**
     * Gets the value of the engineSizeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineSizeUnit() {
        return engineSizeUnit;
    }

    /**
     * Sets the value of the engineSizeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineSizeUnit(String value) {
        this.engineSizeUnit = value;
    }

    /**
     * Gets the value of the designation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignation() {
        return designation;
    }

    /**
     * Sets the value of the designation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignation(String value) {
        this.designation = value;
    }

    /**
     * Gets the value of the isTurboEngine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTurboEngine() {
        return isTurboEngine;
    }

    /**
     * Sets the value of the isTurboEngine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTurboEngine(String value) {
        this.isTurboEngine = value;
    }

    /**
     * Gets the value of the is4X4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIs4X4() {
        return is4X4;
    }

    /**
     * Sets the value of the is4X4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIs4X4(String value) {
        this.is4X4 = value;
    }

    /**
     * Gets the value of the isAllWheelDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAllWheelDrive() {
        return isAllWheelDrive;
    }

    /**
     * Sets the value of the isAllWheelDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String C:\Eldest\AVAutomation\src\test\resources\TestDocument\SaleContract_221011080206.pdf
     *     
     */
    public void setIsAllWheelDrive(String value) {
        this.isAllWheelDrive = value;
    }

    /**
     * Gets the value of the fullCoverageEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullCoverageEndDate() {
        return fullCoverageEndDate;
    }

    /**
     * Sets the value of the fullCoverageEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullCoverageEndDate(String value) {
        this.fullCoverageEndDate = value;
    }

    /**
     * Gets the value of the fullCoverageMaxMile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullCoverageMaxMile() {
        return fullCoverageMaxMile;
    }

    /**
     * Sets the value of the fullCoverageMaxMile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullCoverageMaxMile(String value) {
        this.fullCoverageMaxMile = value;
    }

    /**
     * Gets the value of the powertrainCoverageEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowertrainCoverageEndDate() {
        return powertrainCoverageEndDate;
    }

    /**
     * Sets the value of the powertrainCoverageEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowertrainCoverageEndDate(String value) {
        this.powertrainCoverageEndDate = value;
    }

    /**
     * Gets the value of the powertrainCoverageMaxMile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowertrainCoverageMaxMile() {
        return powertrainCoverageMaxMile;
    }

    /**
     * Sets the value of the powertrainCoverageMaxMile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowertrainCoverageMaxMile(String value) {
        this.powertrainCoverageMaxMile = value;
    }

}
